c = 8+9j # 複數
cc = 0xA21F # 十六進位
ccc = 0o377 # 八進位
cccc = 0b101010 # 二進位
s='這是一個字串' # 單引號也可以
ss="這是另一個字串" # 雙引號也可以
sss="這是一個包含'單引號'的字串" # 雙引號也可以
ssss='這是一個包含"雙引號"的字串' # 單引號也可以
sssss='''這是一個包含'單引號'和"雙引號"的字串''' # 三個單引號也可以
ssssss="""這是一個包含'單引號'和"雙引號"的字串""" # 三個雙引號也可以
print (f"a={c}") # 複數
print (f"cc={cc}") # 十六進位
print (f"ccc={ccc}") # 八進位
print (f"cccc={cccc}") # 二進位
print (f"s={s}") # 字串
print (f"ss={ss}") # 字串
print (f"a.real={c.real}") # 實部
print (f"a.imag={c.imag}") # 虛部
print (f"a.real+a.imag={c.real+c.imag}") # 實部+虛部
print (f"a.conjugate()={c.conjugate()}") # 共軛複數
